### ISSUE TITLE
Hey, can you explain about data used in this

### ISSUE THREAD

**Issue by sharmas1ddharth** [WoutDeleu/ContainerYardAssignment#1]

**Comment by WoutDeleu** [comment]
The data used for this project was provided by our lab supervisor. It represents a realistic port system for cargo transhipments.
There is cargo going in and out of the yard block. The yard block holds all the container groups that need to wait between arrival and departure at the port. Container groups can arrive and depart on land with trucks as well on sea with vessels or boats.
